backend:
  name: github
  repo: 94peter/cms-test # Path to your GitHub repository
  branch: dev

media_folder: "static/images/uploads"

public_folder: "/images/uploads"
i18n:
  structure: multiple_folders
  locales: [en, zh-TW]
  default_locale: zh-TW
collections:
  # - label: "Pages"
  #   name: "pages"
  #   i18n:
  #     structure: single_file
  #     locales: [en, zh-TW]
  #     default_locale: zh-TW
  #   files:
  #     - label: "About Page"
  #       name: "about"
  #       i18n: true
  #       file: "content/{{locale}}/about/_index.md"
  #       fields:
  #         - {label: Title, name: title, widget: string}
  #         - {label: "Body", name: "body", widget: "markdown"}
  #         - {label: "Description", name: "description", widget: "string"}
  - label: "Blog(en)"
    name: "blog(en)"
    folder: "content"
    slug: blog/{{year}}-{{month}}-{{slug}}
    # preview_path: content/{{locale}}/blog/{{slug}}
    create: true
    identifier_field: title
    i18n: true
    fields:
      - {label: "Title", name: "title", widget: "string", i18n: true}
      - {label: "Publish Date", name: "date", widget: "datetime", i18n: duplicate}
      - {label: "Featured Image", name: "image", widget: "image", i18n: true}
      - {label: "Body", name: "body", widget: "markdown", i18n: true}
  - name: NestPages
    label: NestPage
    label_singular: 'NestPage'
    folder: content
    create: true
    # adding a nested object will show the collection folder structure
    nested:
      depth: 300 # max depth to show in the collection tree
      summary: '{{title}}' # optional summary for a tree node, defaults to the inferred title field
    fields:
      - label: Path
        name: path
        widget: string
      - label: Title
        name: title
        widget: string
      - label: Body
        name: body
        widget: markdown
    # adding a meta object with a path property allows editing the path of entries
    # moving an existing entry will move the entire sub tree of the entry to the new location
    meta: { path: { widget: string, label: 'Path', index_file: '_index' } }